spring:
  application:
    name: Mixi-nettyServer
  config:
    import: classpath:application-dev.yml
  profiles:
    active: ${ACTIVE:dev}
server:
  port: 9030
feign:
  httpclient:
    enabled: true
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 100000
        loggerLevel: full
