server:
  port: ${SERVER_PORT:9010}

spring:
  config:
    import: classpath:you-cant-see-that.yml

  profiles:
    active: ${ACTIVE:dev}
  cloud:
    api: true

  mail:
    host: ${EMIAL_HOST:ENC(qMKUwBybaAKewuGZCDYjQw6tCfRVAO5aIQUolS8L06U=)}
    port: ${EMAIL_PORT:ENC(7RRjEe4cBjcETAkyZ6TBh5zwIw6KrEaz)}
    username: ${EMAIL_USERNAME:ENC(Ndpes2aPfHdQQLG2Ds47yIxEh5/YB2ywTbf7UZ8Re7JgCTjwemDMQw==)}
    password: ${EMAIL_PASSWORD:ENC(IFKjNrj7WUsXTiTldZ8TDgHxBxgkYHXBD5RrrjZ2SlGFXMCaObgqgA==)}
    test-connection: false

assistant:
  service:
    id:
      snowflake:
        register: register-redis
        startTime: 2024-07-20 00:00:00
  service-chain:
    serviceMap:
      linkLogin: picCodeVerify->userAgentVerify->emailExistVerify
      linkVerify: userAgentVerify->emailLinkVerify->emailExistVerify[Ignore]

mixi:
  user:
    avatar: "https://tmlgenius.github.io/assistant-docs/img/logo.svg"
    resume: "这个人很懒，什么都没留下"
    nickNamePrefix: "Mixi用户"
    nickNameLen: 10

sa-token:
  token-name: token
  timeout: 259200
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
